//using AngularJSAuthentication.Model;

//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;

//namespace AngularJSAuthentication.API.Controllers
//{
//    public class Helper
//    {

//        public static List<User> CreateUsers()
//        { 
//            List<User> users = new List<AngularJSAuthentication.Model.User>{
//                new User{ age=20, CreatedBy ="Akhilesh1", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh1", LastModifiedBy = DateTime.Now , lastName = "Gandhi1" },
//                new User{ age=20, CreatedBy ="Akhilesh2", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh2", LastModifiedBy = DateTime.Now , lastName = "Gandhi2" },
//                new User{ age=20, CreatedBy ="Akhilesh3", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh3", LastModifiedBy = DateTime.Now , lastName = "Gandhi3" },
//                new User{ age=20, CreatedBy ="Akhilesh4", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh4", LastModifiedBy = DateTime.Now , lastName = "Gandhi4" },
//                new User{ age=20, CreatedBy ="Akhilesh5", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh5", LastModifiedBy = DateTime.Now , lastName = "Gandhi5" },
//                new User{ age=20, CreatedBy ="Akhilesh6", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh6", LastModifiedBy = DateTime.Now , lastName = "Gandhi6" },
//                new User{ age=20, CreatedBy ="Akhilesh7", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh7", LastModifiedBy = DateTime.Now , lastName = "Gandhi7" },
                
//                new User{ age=20, CreatedBy ="Akhilesh8", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh8", LastModifiedBy = DateTime.Now , lastName = "Gandhi8" },
//                new User{ age=20, CreatedBy ="Akhilesh9", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh9", LastModifiedBy = DateTime.Now , lastName = "Gandhi9" },
//                new User{ age=20, CreatedBy ="Akhilesh10", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh10", LastModifiedBy = DateTime.Now , lastName = "Gandhi10" },
//                new User{ age=20, CreatedBy ="Akhilesh11", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh11", LastModifiedBy = DateTime.Now , lastName = "Gandhi11" },
//                new User{ age=20, CreatedBy ="Akhilesh12", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh12", LastModifiedBy = DateTime.Now , lastName = "Gandhi12" },
//                new User{ age=20, CreatedBy ="Akhilesh13", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh13", LastModifiedBy = DateTime.Now , lastName = "Gandhi13" },
//                new User{ age=20, CreatedBy ="Akhilesh14", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh14", LastModifiedBy = DateTime.Now , lastName = "Gandhi14" },
//                new User{ age=20, CreatedBy ="Akhilesh15", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh15", LastModifiedBy = DateTime.Now , lastName = "Gandhi15" },
//                new User{ age=20, CreatedBy ="Akhilesh16", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh16", LastModifiedBy = DateTime.Now , lastName = "Gandhi16" },
//                new User{ age=20, CreatedBy ="Akhilesh17", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh17", LastModifiedBy = DateTime.Now , lastName = "Gandhi17" },
//                new User{ age=20, CreatedBy ="Akhilesh18", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh18", LastModifiedBy = DateTime.Now , lastName = "Gandhi18" },
//                new User{ age=20, CreatedBy ="Akhilesh19", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh19", LastModifiedBy = DateTime.Now , lastName = "Gandhi19" },
//                new User{ age=20, CreatedBy ="Akhilesh20", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh20", LastModifiedBy = DateTime.Now , lastName = "Gandhi20" },
//                new User{ age=20, CreatedBy ="Akhilesh21", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh21", LastModifiedBy = DateTime.Now , lastName = "Gandhi21" },
//                new User{ age=20, CreatedBy ="Akhilesh22", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh22", LastModifiedBy = DateTime.Now , lastName = "Gandhi22" },
//                new User{ age=20, CreatedBy ="Akhilesh23", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh23", LastModifiedBy = DateTime.Now , lastName = "Gandhi23" },
//                new User{ age=20, CreatedBy ="Akhilesh24", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh24", LastModifiedBy = DateTime.Now , lastName = "Gandhi24" },
//                new User{ age=20, CreatedBy ="Akhilesh25", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh25", LastModifiedBy = DateTime.Now , lastName = "Gandhi25" },
//                new User{ age=20, CreatedBy ="Akhilesh26", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh26", LastModifiedBy = DateTime.Now , lastName = "Gandhi26" },
//                new User{ age=20, CreatedBy ="Akhilesh27", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh27", LastModifiedBy = DateTime.Now , lastName = "Gandhi27" },
//                new User{ age=20, CreatedBy ="Akhilesh28", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh28", LastModifiedBy = DateTime.Now , lastName = "Gandhi28" },
//                new User{ age=20, CreatedBy ="Akhilesh29", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh29", LastModifiedBy = DateTime.Now , lastName = "Gandhi29" },
//                new User{ age=20, CreatedBy ="Akhilesh30", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh30", LastModifiedBy = DateTime.Now , lastName = "Gandhi30" },
//                new User{ age=20, CreatedBy ="Akhilesh31", CreatedDate = DateTime.Now , customerId =1 , firstName ="Akhilesh31", LastModifiedBy = DateTime.Now , lastName = "Gandhi31" },
//        };
//            return users;
//        }
//        public static List<Video> CreateVideos()
//        {
//            List<Video> Videos = new List<Video>{        new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/aQipuiTcn3U/hqdefault.jpg", title = "Julie Ralph - End to End Angular Testing with Protractor", url ="https://www.youtube.com/watch?v=aQipuiTcn3U" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/srt3OBP2kGc/hqdefault.jpg", title = "Angular Team Panel", url ="https://www.youtube.com/watch?v=srt3OBP2kGc" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/hC0MpgUoui4/hqdefault.jpg", title = "Lukas Rubbelke & Matias Niemela - Awesome Interfaces with AngularJS Animations", url ="https://www.youtube.com/watch?v=hC0MpgUoui4" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/_OGGsf1ZXMs/hqdefault.jpg", title = "Vojta Jina - Dependency Injection", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=_OGGsf1ZXMs" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 1 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 2 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 3 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 4 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 5 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 6 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 7 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 8 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 9 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 10 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 11 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 12 },
//               new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 13 },
//                new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 14 },
//                 new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 15 },
//                  new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 16 },
//                   new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 17 },
//                  new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 18 },
//                  new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 19 },
//                 new Video {     imageUrl = "https://i.ytimg.com/vi/r1A1VR0ibIQ/hqdefault.jpg", title = "Miško Hevery and Brad Green - Keynote", url ="https://www.youtube.com/watch?v=r1A1VR0ibIQ" , CreatedBy ="Akhilesh",CreatedDate = DateTime.Now , discription ="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", UpdateBy ="Akhilesh", UpdatedDate = DateTime.Now , videoId = 20 },


//        };
//            return Videos;
//        }

//        //public static List<Customer> CreateCustomers()
//        //{
//        //    List<Customer> OrderList = new List<Customer> 
//        //    {
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
               
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },

//        //           new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" },
//        //         new Customer {CustomerId = 10248, Name = "Taiseer 1 Joudeh", Description = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",LastModifiedBy="Akhilesh" }
              
              
//        //    };

//        //    return OrderList;
//        //}
//        //public static List<Project> CreateProjects()
//        //{
//        //    List<Project> OrderList = new List<Project> 
//        //    {
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
               
//        //        new Project {ProjectID = 10248, ProjectName = "Taiseer 1 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10241, ProjectName = "Taiseer 2 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10242, ProjectName = "Taiseer3 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10243, ProjectName = "Taiseer4  Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10244, ProjectName = "Taiseer5 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" },
//        //       new Project {ProjectID = 10245, ProjectName = "Taiseer 6 Joudeh", Discription = "Amman",CreatedDate = DateTime.Now,UpdatedDate =DateTime.Now,CreatedBy ="Akhilesh",UpdateBy="Akhilesh" }
              
//        //    };

//        //    return OrderList;
//        //}
//    }
//}